@startuml
title AsteroidsFX Component Diagram
header Version 1.0 - Documentation
footer Diagram generated on: 2024-05-13

skinparam linetype polyline
skinparam arrowthickness 2

package "AsteroidsFX" {
    ' Modules:
    [Core]

    [Asteroid]
    [Bullet]
    [Collision]
    [Enemy]
    [Player]

    component "Score (Microservice)" {
      portin "ScoreService Server"
    }

    [CommonBullet]
    [Common]

    ' Interfaces:
    interface IGamePluginService #000080
    interface IEntityProcessingService #FF7F50
    interface IPostEntityProcessingService #98FF98

    ' Relations:
    [Core] --down-( IGamePluginService #000080
    [Core] --down-( IEntityProcessingService #FF7F50
    [Core] --down-( IPostEntityProcessingService #98FF98
    [Core] ..down..> [Common]

    ' Asteroid:
    [Asteroid] --up-- IGamePluginService #000080
    [Asteroid] --up-- IEntityProcessingService #FF7F50
    [Asteroid] ..down..> [Common]

    ' Bullet:
    [Bullet] --up-- IGamePluginService #000080
    [Bullet] --up-- IEntityProcessingService #FF7F50
    [Bullet] ..down..> [Common]

    ' Enemy:
    [Enemy] --up-- IGamePluginService #000080
    [Enemy] --up-- IEntityProcessingService #FF7F50
    [Enemy] ..down..> [Common]
    [CommonBullet] ...> [Enemy] : "Dependency\nInjection"

    ' Player:
    [Player] --up-- IGamePluginService #000080
    [Player] --up-- IEntityProcessingService #FF7F50
    [Player] ..down..> [Common]
    [CommonBullet] ...> [Player] : "Dependency\nInjection"

    ' Collision:
    [Collision] --up-- IGamePluginService #000080
    [Collision] --up-- IPostEntityProcessingService #98FF98
    [Collision] ..down..> [Common]

    ' CommonBullet
    [CommonBullet] ..down..> [Common]

    ' Score:
    "ScoreService Server" <-left-> [Core] : HTTP Requests
}

package Legend {
    package Entities {
        component "Component" {
            portin Endpoint
        }
        () Interface
    }

    package Relations {
        [C1]
        () I1 #000080
        [C1] -right-( I1 #000080 : Require
        [C1] -[hidden]down- [C2]

        [C2]
        () I2 #FF7F50
        [C2] -right- I2 #FF7F50 : Provides
        [C2] -[hidden]down- [C3]

        [C3]
        () Binding #98FF98
        [C4]
        [C3] -right( Binding #98FF98 : Require
        Binding -right- [C4]  #98FF98 : Provides
        [C3] -[hidden]down- [C5]

        [C5]
        [C6]
        [C5] .right.> [C6] : Dependency or Injection
        [C5] -[hidden]down- [C8]

        component "C7" {
            portin EP1
        }
        [C8]
        EP1 <--[hidden]left--> [C8]
        EP1 <--left--> [C8] : HTTP Requests
    }

    Interface -[hidden]down-> Relations
    "Component" -[hidden]down-> Relations
}
@enduml
